version: 2.1

orbs:
  heroku: circleci/heroku@1.2.2

executors:
  flask-exam-test:
    working_directory: /home/mo/circulate
    docker:
      - image: python:3.8.5
        environment:
          FLASK_APP: autoapp.py
          FLASK_DEBUG: 1
  flask-exam:
    working_directory: /home/mo/circulate
    docker:
      - image: python:3.8.5
        environment:
          FLASK_APP: autoapp.py
          FLASK_DEBUG: 0
          DATABASE_URL: 'postgresql://root@localhost/example'
      - image: circleci/postgres:9.4.12-alpine


jobs:
  test:
    executor: flask-exam-test
    steps:
      - checkout
      - run:
          name: install deps
          command: pip install -r requirements/dev.txt
      - run:
          name: run tests
          command: flask test
      - store_test_results:
          path: test-results
  build:
    executor: flask-exam
    steps:
      - checkout
      - run:
          name: install deps
          command: pip install -r requirements.txt

  # deploy:
  #   executor: flask-exam

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: master
