version: 2
jobs:
  build:
    working_directory: /home/jimmychen/circulate
    docker:
      - image: python:3.8.5
        environment:
          FLASK_APP: autoapp.py
          FLASK_DEBUG: 1
    steps:
      - checkout
      - run:
          name: install deps
          command: pip install -r requirements/dev.txt

      - run:
          name: run tests
          command: flask test
      - store_test_results:
          path: test-results

